version: '3'

services:
  app:
    image: crewcompany/crew-application:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
