import { Contact } from '../entities';
import { Column } from 'typeorm';

export enum ERROR_MESSAGES {
  ERROR_CONTACT_NOT_FOUND = 'CONTACT_NOT_FOUND',
  ERROR_CONTACT_ALREADY_EXIST = 'CONTACT_ALREADY_EXIST',
  ERROR_FIRST_NAME_REQUIRED = 'FIRST_NAME_REQUIRED',
  ERROR_LAST_NAME_REQUIRED = 'LAST_NAME_REQUIRED',
  ERROR_COMPANY_NAME_REQUIRED = 'COMPANY_NAME_REQUIRED',
  ERROR_INVALID_FIRST_NAME_FORMAT = 'INVALID_EMAIL_FORMAT',
  ERROR_INVALID_LAST_NAME_FORMAT = 'INVALID_EMAIL_FORMAT',
  ERROR_INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  ERROR_INVALID_PHONE_FORMAT = 'INVALID_PHONE_FORMAT',
  ERROR_INVALID_ISPRIMARY_FORMAT = 'INVALID_ISPRIMARY_FORMAT',
  ERROR_CONTACT_IS_PRIMARY = 'CONTACT_IS_PRIMARY',
}

export enum ContactRelationEnum {
  BRANCH = 'branch',
  ORDERS = 'orders',
  BRANCH_ORGANIZATION = 'branch.organization',
  SKUREQUESTS = 'skuRequests',
}

export const OrderFields: Array<keyof Contact> = ['firstName', 'lastName', 'email', 'phone', 'isPrimary'];
