export enum COMMON_ERRORS_MESSAGES {
  ERRORS_INVALID_TOKEN = 'INVALID_TOKEN',

  ERRORS_INVALID_ID = 'INVALID_ID',

  ERRORS_FORBIDDEN = 'FORBIDDEN',
}

export const NOT_LOG_ERROR = 'NOT_LOG_ERROR';
